export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const ROOM_SEARCH_REQUEST = 'ROOM_SEARCH_REQUEST'
export const ROOM_SEARCH_SUCCESS = 'ROOM_SEARCH_SUCCESS'
export const ROOM_SEARCH_FAILURE = 'ROOM_SEARCH_FAILURE'

export const ROOM_LOADMORE_REQUEST = "ROOM_LOADMORE_REQUEST";
export const ROOM_LOADMORE_SUCCESS = "ROOM_LOADMORE_SUCCESS";
export const ROOM_LOADMORE_FAILURE = "ROOM_LOADMORE_FAILURE";

export const ROOM_DETAIL_REQUEST = "ROOM_DETAIL_REQUEST";
export const ROOM_DETAIL_SUCCESS = "ROOM_DETAIL_SUCCESS";
export const ROOM_DETAIL_FAILURE = "ROOM_DETAIL_FAILURE";

export const BOOK_ROOM_REQUEST = 'BOOK_ROOM_REQUEST'
export const BOOK_ROOM_SUCCESS = 'BOOK_ROOM_SUCCESS'
export const BOOK_ROOM_FAILURE = 'BOOK_ROOM_FAILURE'
  
export const RESPONSE_SECRETARY_REQUEST = 'RESPONSE_SECRETARY_REQUEST'
export const RESPONSE_SECRETARY_SUCCESS = 'RESPONSE_SECRETARY_SUCCESS'
export const RESPONSE_SECRETARY_FAILURE = 'RESPONSE_SECRETARY_FAILURE'

export const RESPONSE_DRINKS_REQUEST = 'RESPONSE_DRINKS_REQUEST'
export const RESPONSE_DRINKS_SUCCESS = 'RESPONSE_DRINKS_SUCCESS'
export const RESPONSE_DRINKS_FAILURE = 'RESPONSE_DRINKS_FAILURE'

export const RESPONSE_AUDIO_REQUEST = 'RESPONSE_AUDIO_REQUEST'
export const RESPONSE_AUDIO_SUCCESS = 'RESPONSE_AUDIO_SUCCESS'
export const RESPONSE_AUDIO_FAILURE = 'RESPONSE_AUDIO_FAILURE'
